export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <script src="https://cdn.tailwindcss.com"></script>
        <script
          src="https://static.elfsight.com/platform/platform.js"
          data-use-service-core
          defer
        ></script>
        <body>{children}</body>
      </html>
    );
  }