export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
  };

  export default function RootLayout({ children }) {
    if (typeof window !== "undefined") {
      console.log(localStorage.getItem("token"));
    }
    return (
      <html lang="en">
     <head><script src="https://cdn.tailwindcss.com"></script>
        <script
          src="https://static.elfsight.com/platform/platform.js"
          data-use-service-core
          defer
        ></script></head>   
        <body suppressHydrationWarning={true} >{children}</body>
      </html>
    );
  }